

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fibonacciSum(n) {
    let i = 1, j = 2, next;
    sum = 0;
    while (i <= n) {
        if (i % 2 == 0) {
            sum += i;
        }
        next = i + j;
        i = j;
        j = next;
    }

    return sum;

}

console.log(fibonacciSum(4000000));
